name: CD

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - synchronize
      - opened

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  plugin_zip:
    name: Create archive
    runs-on: ubuntu-20.04
    env:
      OUTPUT: High DPI Continuous.zip
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Create archive
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'High DPI Continuous.zip'
          exclusions: '*.git*'
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OUTPUT }}
          path: ${{ env.OUTPUT }}
