name: Check

on:
  push:
    branches:
      - master
      - releases/v[0-9]+.[0-9]+.[0-9]+
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  validate_copyright:
    name: Copyright
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        show-progress: false
    - name: Validate copyright file with debian-control-linter
      uses: tibetiroka/debian-control-linter-action@v1
      with:
        type: 'debian/copyright'
        file: 'copyright'
        preset: 'strict'
        enable: 'trailingSpace,upstreamContactStyle,urlForceHttps,fieldNameCapitalization,maintainerNameFullStop,urlExists,copyrightSourceStyle'
