name: Check Endless Sky Low DPI Assets
on:
  push:
    branches:
      - master
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  search_es_assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Find Low DPI Images in ES master branch
        run: ./scripts/find-low-dpi-images.sh
